### ISSUE TITLE
Example in test.js not working

### ISSUE THREAD

**Issue by wonderlandpark** [cotwo0139/spagination#2]
While trying line in `test.js`,
Footer is shown as null

The Line is:
https://github.com/cotwo0139/spagination/blob/2f4cb01eaf2720602bf1f6a615f77d16430c28c4/test.js#L7

**Comment by cotwo0139** [comment]
에러 확인을 위해 에러 내용과 사용한 소스코드의 일부를 보여주세요.

**Comment by wonderlandpark** [comment]
N9 error has been occurred and the footer is returned as null.
Source code is the same with the `test.js`

**Comment by wonderlandpark** [comment]
Well Source Code is https://github.com/wonderlandpark/wonderbot/blob/c7979d677d6d2c62be9fffc568f530b803b42574/commands/season/mask.js#L24
