### ISSUE TITLE
Error: embed is must be Discord.MessageEmbed

### ISSUE THREAD

**Issue by Zero-Brazil734** [cotwo0139/spagination#3]
![image](https://user-images.githubusercontent.com/51540538/77110409-4fd51700-6a04-11ea-8f6f-4f5df774ba11.png)

It seems that the operator "instanceof" not seeing this as MessageEmbed class to an instance of MessageEmbed.

p.s: The "Discord" variable is equal to `require("discord.js")`

**Comment by cotwo0139** [comment]
Fixed c5a4bdf
